### ISSUE TITLE
Crash when scrolling

### ISSUE THREAD

**Issue by hojjatabdollahi** [cosmic-utils/clipboard-manager#103]
Scrolling on the list causes a crash. I have some text (mostly code) and an image in the list. I also have some empty screen shots which are because of the new bug in xdg-desktop-portal-cosmic which copies a corrupted image into the clipboard.

Here is what I see in the logs:
```
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: thread 'main' panicked at core/src/slice/sort/shared/smallsort.rs:860:5:
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: user-provided comparison function does not correctly implement a total order
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: stack backtrace:
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    0: rust_begin_unwind
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    1: core::panicking::panic_fmt
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    2: core::slice::sort::shared::smallsort::panic_on_ord_violation
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    3: core::slice::sort::shared::smallsort::bidirectional_merge
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    4: core::slice::sort::stable::quicksort::quicksort
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    5: core::slice::sort::stable::drift::sort
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    6: core::slice::sort::stable::driftsort_main
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    7: iced_graphics::damage::group
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    8: <iced_tiny_skia::window::compositor::Compositor as iced_graphics::compositor::Compositor>::present
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:    9: iced_winit::program::run_instance::{{closure}}
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   10: iced_winit::program::run::Runner<Message,F,C>::process_event
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   11: winit::platform_impl::linux::wayland::event_loop::EventLoop::single_iteration
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   12: winit::platform_impl::linux::wayland::event_loop::EventLoop::run_app
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   13: iced_winit::program::run
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   14: cosmic::applet::run
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager:   15: cosmic_ext_applet_clipboard_manager::main
Nov 21 14:45:59 pop-os cosmic-panel[28198]: io.github.wiiznokes.cosmic-ext-applet-clipboard-manager: note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by wiiznokes** [comment]
Could you by any chance attach the db in this github issue ? It should be `~/.cache/cosmic-ext-applet-clipboard-manager/io.github.wiiznokes.cosmic-ext-applet-clipboard-manager-db-4.sqlite`.

I will try to fix even if you can't/don't want to provide it

**Comment by wiiznokes** [comment]
hum, i'm starting to think it's an upstream bug. The db would still help to see if i can reproduce tho

**Comment by hojjatabdollahi** [comment]
Here is the db.
[db.tar.gz](https://github.com/user-attachments/files/17894703/db.tar.gz)

**Comment by wiiznokes** [comment]
Thanks! Apparently its an upstream Iced bug that have been fixed. We just need to wait that the pop os fork get rebased on iced master

**Comment by wiiznokes** [comment]
In the mean time, ig you could compile the applet with a rust compiler < 1.81.0 to fix this

**Comment by hojjatabdollahi** [comment]
Unfortunately can't compile with 1.80.
```
   Compiling idna v1.0.3
error[E0658]: use of unstable library feature 'error_in_core'
  --> /home/hojjat/.cargo/registry/src/index.crates.io-6f17d22bba15001f/idna-1.0.3/src/lib.rs:78:6
   |
78 | impl core::error::Error for Errors {}
```

**Comment by wiiznokes** [comment]
Hum yeah, ig we will have to wait then

**Comment by hojjatabdollahi** [comment]
It is fixed. Thank you.
